basePath: /api/v1
definitions:
  pkg.sectionLevel:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  v1.Error:
    properties:
      error:
        type: string
    type: object
  v1.Success:
    properties:
      status:
        type: string
    type: object
externalDocs:
  description: JestHub Documentation
  url: https://jesthub.sh/docs
host: localhost:8080
info:
  contact:
    email: petar.nikolovski@protonmail.com
    name: Petar Nikolovski
    url: https://jesthub.sh/support
  description: Store and reuse your CLI commands.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://jesthub.sh/terms/
  title: Jester API
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/json
      description: post data to get a JWT token
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Error'
      summary: Login a user
      tags:
      - auth
  /auth/register:
    post:
      consumes:
      - application/json
      description: post data for user registration
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/v1.Success'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/v1.Error'
      summary: Register a new user
      tags:
      - auth
  /section/levels:
    get:
      consumes:
      - application/json
      description: get all levels
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pkg.sectionLevel'
            type: array
      summary: List possible levels for sections
      tags:
      - sections
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
