basePath: /api/v1
definitions:
  pkg.sectionLevel:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: petar.nikolovski@protonmail.com
    name: Petar Nikolovski
    url: https://jesthub.sh/support
  description: Store and reuse your CLI commands.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://jesthub.sh/terms/
  title: Jester API
  version: "1.0"
paths:
  /section/levels:
    get:
      consumes:
      - application/json
      description: get all levels
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/pkg.sectionLevel'
            type: array
      summary: List possible levels for sections
      tags:
      - levels
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
